### ISSUE TITLE
Missing aggregate grade recalculation after grade transfer to group members

### ISSUE THREAD

**Issue by jondo** [academic-moodle-cooperation/moodle-mod_grouptool#26]
Yesterday, it happened to me that after transferring the grades of one assignment to the other group members the overall course grade was not updated.

My sysadmin told me she managed to reproduce this in a test environment.
Our workaround for now was to trigger course grade re-computation manually by changing something in the grade setup, then undoing that change.

**Comment by goggo24** [comment]
Thanks for reporting. We will try to reproduce it.

**Comment by goggo24** [comment]
We were able to reproduce it and will add it to our backlog. It should be fixed with the next version.

**Comment by goggo24** [comment]
Fixed already in v.4.0.1. - backporting to v.3.11.5 will come soon.

**Comment by jondo** [comment]
did this actually make version 3.11.5? In which commit? This could be a good updating reason for our sysadmin @LisaE14.

**Comment by jondo** [comment]
@LisaE14, which version are we currently using? I am still seeing this issue.

**Comment by LisaE14** [comment]
@jondo at the moment we use 3.11.0. Our next update is in August. Then this problem will be fixed.
